---
- name: Inputs for static routes task
  include_tasks: static_route.yml
  with_items:
    - { vpc_uuid: "{{vpc_uuids[0]}}", subnet_name: Ext-Nat, destination: "10.2.2.0/24"}
    - { vpc_uuid: "{{vpc_uuids[1]}}", subnet_name: Ext-Nat, destiantion: "10.2.3.0/24"}
